"""rename column in Student model

Revision ID: e34558bd8ce1
Revises: 791279dd0760
Create Date: 2023-06-05 23:53:43.400579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34558bd8ce1'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade():
    # Rename the column using the op.alter_column() command
    op.alter_column('scholars', 'old_column', new_column_name='new_column')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scholars', 'new_column', new_column_name='old_column')
    # ### end Alembic commands ###
